services:
  pgdatabase:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Mek.920422
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    
docker run -it \
-e POSTGRES_USER="sa" \
-e POSTGRES_PASSWORD="Mek.920422" \
-e POSTGRES_DB="by_taxi" \
-v ./ny_taxi_postgres_data:/var/lib/postgresql/data \
-p 5432:5432 \
--network=pg-network \
--name pg-database \
postgres:14.5

docker run -it \
-e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
-e PGADMIN_DEFAULT_PASSWORD="Mek.920422" \
-p 8080:80 \
--network=pg-network \
--name pgadmin \
dpage/pgadmin4

URL="https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet"

python upload-data.py \
    --user=sa \
    --pw=Mek.920422 \
    --host=localhost \
    --port=5432 \
    --db=by_taxi \
    --table=yellow_taxi_trips \
    --url=${URL}